<a href="https://colab.research.google.com/github/yakupusame/Greeting_Classification/blob/main/Greetings_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('tagged_selections_by_sentence.csv')

In [2]:
df.head(3)

Dataset  Partition  SentenceID  ...  Gratitude Other Express Emotion
0        1          1        2227  ...          0     1               0
1        1          1        2182  ...          0     1               0
2        1          1        2191  ...          0     0               0

[3 rows x 14 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6759 entries, 0 to 6758
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Dataset           6759 non-null   int64 
 1   Partition         6759 non-null   int64 
 2   SentenceID        6759 non-null   int64 
 3   Threshold         6759 non-null   int64 
 4   MergedSelections  6759 non-null   object
 5   Unselected        6725 non-null   object
 6   Selected          3790 non-null   object
 7   Greeting          6759 non-null   int64 
 8   Backstory         6759 non-null   int64 
 9   Justification     6759 non-null   int64 
 10  Rant              6759 non-null   int64 
 11  Gratitude         6759 non-null   int64 
 12  Other             6759 non-null   int64 
 13  Express Emotion   6759 non-null   int64 
dtypes: int64(11), object(3)
memory usage: 739.4+ KB


In [4]:
df['Dataset'].value_counts()

4    1851
3    1843
2    1799
1    1266
Name: Dataset, dtype: int64

In [5]:
df_greeting = df[df['Greeting'] == 1]

In [6]:
df_greeting['Selected']

6       Hello,  In the fall we had a two week vacation...
14      Hi! I've heard horrid stories abt flight cance...
15      Hi, can anyone help. I have never travelled be...
19      Hi everyone, A quick question - we have booked...
23      Hey, I'm going to Japan on the 24th of June fo...
                              ...                        
6711                                                 hi, 
6713                                                  hi 
6718                                                 Hi. 
6728    Hello,  I do not think any cords are lose in t...
6730                                                 HI, 
Name: Selected, Length: 802, dtype: object

In [7]:
df.head()

Dataset  Partition  SentenceID  ...  Gratitude Other Express Emotion
0        1          1        2227  ...          0     1               0
1        1          1        2182  ...          0     1               0
2        1          1        2191  ...          0     0               0
3        1          1        2183  ...          0     0               0
4        1          1        2198  ...          0     0               0

[5 rows x 14 columns]

In [8]:
# We can drop columns Dataset , Partition,SentenceID, Threshold,MergedSelections and Unselected
# Because they will not affect Greeting column
df.drop(['Dataset','Partition','SentenceID','Threshold','MergedSelections','Unselected'],axis = 1 , inplace=True)

In [9]:
df.head()

Selected  ...  Express Emotion
0  Just to set the scene... I have a fairly tall ...  ...                0
1  We already have allocated seats, so as far as ...  ...                0
2                                                NaN  ...                0
3  My family is flying from Hartford Ct to Honolu...  ...                0
4                                                NaN  ...                0

[5 rows x 8 columns]

In [10]:
df.dropna(axis=0,inplace=True)

In [11]:
df.isnull().sum()

Selected           0
Greeting           0
Backstory          0
Justification      0
Rant               0
Gratitude          0
Other              0
Express Emotion    0
dtype: int64

In [12]:
df.head

<bound method NDFrame.head of                                                Selected  ...  Express Emotion
0     Just to set the scene... I have a fairly tall ...  ...                0
1     We already have allocated seats, so as far as ...  ...                0
3     My family is flying from Hartford Ct to Honolu...  ...                0
5     I knew United did not have seat back TVs or a ...  ...                0
6     Hello,  In the fall we had a two week vacation...  ...                0
...                                                 ...  ...              ...
6743                    i need to make service changes.  ...                0
6752                                          How do I.  ...                0
6753  - keeps timing out when asking me to update my...  ...                1
6755                        when we are out f the area?  ...                0
6756                     because I do't understand how.  ...                0

[3790 rows x 8 columns]>

In [13]:
sentences = df['Selected'].tolist()
len(sentences)

3790

In [14]:
one_string_sentences = "".join(sentences)
one_string_sentences

'Just to set the scene... I have a fairly tall husband who likes to complain on long flights when his legs are hurting him. In the past we have been lucky in getting the seat next to the exits with the extra legroom on scheduled flights on a few occasions. I recall getting these seats when we asked politely at the check in desk. Ideally, we would love to get these seats when we travel to Bangkok (economy) - although I know there is no guarantee and after reading posts they can be allocated to passengers with \'elite\' status etc I believe these seats are only assigned by the airport check in staff on the day (or at least this is what I thought I read on the Emirates website). We have selected the next best seats for us through the online booking manager system. My question is therefore this -We already have allocated seats, so as far as I can see the only extra thing that online check-in offers is that you don\'t have to have your boarding pass printed at the check-in desk. Things that

In [15]:
import string
string.punctuation


'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [16]:
df_punctuation_removed = [char for char in one_string_sentences if char not in string.punctuation]
df_punctuation_removed

['J',
 'u',
 's',
 't',
 ' ',
 't',
 'o',
 ' ',
 's',
 'e',
 't',
 ' ',
 't',
 'h',
 'e',
 ' ',
 's',
 'c',
 'e',
 'n',
 'e',
 ' ',
 'I',
 ' ',
 'h',
 'a',
 'v',
 'e',
 ' ',
 'a',
 ' ',
 'f',
 'a',
 'i',
 'r',
 'l',
 'y',
 ' ',
 't',
 'a',
 'l',
 'l',
 ' ',
 'h',
 'u',
 's',
 'b',
 'a',
 'n',
 'd',
 ' ',
 'w',
 'h',
 'o',
 ' ',
 'l',
 'i',
 'k',
 'e',
 's',
 ' ',
 't',
 'o',
 ' ',
 'c',
 'o',
 'm',
 'p',
 'l',
 'a',
 'i',
 'n',
 ' ',
 'o',
 'n',
 ' ',
 'l',
 'o',
 'n',
 'g',
 ' ',
 'f',
 'l',
 'i',
 'g',
 'h',
 't',
 's',
 ' ',
 'w',
 'h',
 'e',
 'n',
 ' ',
 'h',
 'i',
 's',
 ' ',
 'l',
 'e',
 'g',
 's',
 ' ',
 'a',
 'r',
 'e',
 ' ',
 'h',
 'u',
 'r',
 't',
 'i',
 'n',
 'g',
 ' ',
 'h',
 'i',
 'm',
 ' ',
 'I',
 'n',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'p',
 'a',
 's',
 't',
 ' ',
 'w',
 'e',
 ' ',
 'h',
 'a',
 'v',
 'e',
 ' ',
 'b',
 'e',
 'e',
 'n',
 ' ',
 'l',
 'u',
 'c',
 'k',
 'y',
 ' ',
 'i',
 'n',
 ' ',
 'g',
 'e',
 't',
 't',
 'i',
 'n',
 'g',
 ' ',
 't',
 'h',
 'e',
 ' ',
 's',
 'e'

In [17]:
df_removed = "".join(df_punctuation_removed)
df_removed

'Just to set the scene I have a fairly tall husband who likes to complain on long flights when his legs are hurting him In the past we have been lucky in getting the seat next to the exits with the extra legroom on scheduled flights on a few occasions I recall getting these seats when we asked politely at the check in desk Ideally we would love to get these seats when we travel to Bangkok economy  although I know there is no guarantee and after reading posts they can be allocated to passengers with elite status etc I believe these seats are only assigned by the airport check in staff on the day or at least this is what I thought I read on the Emirates website We have selected the next best seats for us through the online booking manager system My question is therefore this We already have allocated seats so as far as I can see the only extra thing that online checkin offers is that you dont have to have your boarding pass printed at the checkin desk Things that are putting me off are 1

In [18]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [19]:
df_removed = [word for word in df_removed.split() if word.lower() not in stopwords.words('english')]
df_removed

['set',
 'scene',
 'fairly',
 'tall',
 'husband',
 'likes',
 'complain',
 'long',
 'flights',
 'legs',
 'hurting',
 'past',
 'lucky',
 'getting',
 'seat',
 'next',
 'exits',
 'extra',
 'legroom',
 'scheduled',
 'flights',
 'occasions',
 'recall',
 'getting',
 'seats',
 'asked',
 'politely',
 'check',
 'desk',
 'Ideally',
 'would',
 'love',
 'get',
 'seats',
 'travel',
 'Bangkok',
 'economy',
 'although',
 'know',
 'guarantee',
 'reading',
 'posts',
 'allocated',
 'passengers',
 'elite',
 'status',
 'etc',
 'believe',
 'seats',
 'assigned',
 'airport',
 'check',
 'staff',
 'day',
 'least',
 'thought',
 'read',
 'Emirates',
 'website',
 'selected',
 'next',
 'best',
 'seats',
 'us',
 'online',
 'booking',
 'manager',
 'system',
 'question',
 'therefore',
 'already',
 'allocated',
 'seats',
 'far',
 'see',
 'extra',
 'thing',
 'online',
 'checkin',
 'offers',
 'dont',
 'boarding',
 'pass',
 'printed',
 'checkin',
 'desk',
 'Things',
 'putting',
 '1',
 'Ive',
 'noticed',
 'past',
 'couple'

In [20]:
# Let's define a pipeline to clean up all the messages 
# The pipeline performs the following: (1) remove punctuation, (2) remove stopwords
def message_cleaning(message):
    Test_punc_removed = [char for char in message if char not in string.punctuation]
    Test_punc_removed_join = ''.join(Test_punc_removed)
    Test_punc_removed_join_clean = [word for word in Test_punc_removed_join.split() if word.lower() not in stopwords.words('english')]
    return Test_punc_removed_join_clean

In [21]:
df.head()

Selected  ...  Express Emotion
0  Just to set the scene... I have a fairly tall ...  ...                0
1  We already have allocated seats, so as far as ...  ...                0
3  My family is flying from Hartford Ct to Honolu...  ...                0
5  I knew United did not have seat back TVs or a ...  ...                0
6  Hello,  In the fall we had a two week vacation...  ...                0

[5 rows x 8 columns]

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
# Define the cleaning pipeline we defined earlier
vectorizer = CountVectorizer(analyzer = message_cleaning)
df_all = vectorizer.fit_transform(df['Selected'])


In [23]:
print(df_all.toarray()) 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [24]:
df_all.shape

(3790, 8954)

In [25]:
df.head()

Selected  ...  Express Emotion
0  Just to set the scene... I have a fairly tall ...  ...                0
1  We already have allocated seats, so as far as ...  ...                0
3  My family is flying from Hartford Ct to Honolu...  ...                0
5  I knew United did not have seat back TVs or a ...  ...                0
6  Hello,  In the fall we had a two week vacation...  ...                0

[5 rows x 8 columns]

In [26]:
df.drop(['Selected'],axis = 1 ,inplace=True)
df_1 = pd.DataFrame(df_all.toarray())
df_final = pd.concat([df_1,df],axis = 1)
df_final

0    1    2    3  ...  Rant  Gratitude  Other  Express Emotion
0     0.0  0.0  0.0  0.0  ...   0.0        0.0    1.0              0.0
1     0.0  0.0  0.0  0.0  ...   0.0        0.0    1.0              0.0
2     0.0  0.0  0.0  0.0  ...   NaN        NaN    NaN              NaN
3     0.0  0.0  0.0  0.0  ...   0.0        0.0    0.0              0.0
4     0.0  0.0  0.0  0.0  ...   NaN        NaN    NaN              NaN
...   ...  ...  ...  ...  ...   ...        ...    ...              ...
6743  NaN  NaN  NaN  NaN  ...   0.0        0.0    1.0              0.0
6752  NaN  NaN  NaN  NaN  ...   0.0        0.0    1.0              0.0
6753  NaN  NaN  NaN  NaN  ...   1.0        0.0    0.0              1.0
6755  NaN  NaN  NaN  NaN  ...   0.0        0.0    1.0              0.0
6756  NaN  NaN  NaN  NaN  ...   0.0        0.0    1.0              0.0

[5473 rows x 8961 columns]

In [27]:
df_final.dropna(inplace=True)

In [28]:
x = df_final.drop(['Greeting'],axis=1)
x

0    1    2    3  ...  Rant  Gratitude  Other  Express Emotion
0     0.0  0.0  0.0  0.0  ...   0.0        0.0    1.0              0.0
1     0.0  0.0  0.0  0.0  ...   0.0        0.0    1.0              0.0
3     0.0  0.0  0.0  0.0  ...   0.0        0.0    0.0              0.0
5     0.0  0.0  0.0  0.0  ...   0.0        0.0    1.0              0.0
6     0.0  0.0  0.0  0.0  ...   1.0        1.0    0.0              0.0
...   ...  ...  ...  ...  ...   ...        ...    ...              ...
3780  0.0  0.0  0.0  0.0  ...   0.0        0.0    0.0              0.0
3781  0.0  0.0  0.0  0.0  ...   0.0        0.0    0.0              0.0
3785  0.0  0.0  0.0  0.0  ...   0.0        1.0    1.0              0.0
3788  0.0  0.0  0.0  0.0  ...   0.0        0.0    0.0              0.0
3789  0.0  0.0  0.0  0.0  ...   0.0        0.0    0.0              0.0

[2107 rows x 8960 columns]

In [29]:
y = df_final['Greeting']
y

0       0.0
1       0.0
3       0.0
5       0.0
6       1.0
       ... 
3780    0.0
3781    1.0
3785    0.0
3788    0.0
3789    0.0
Name: Greeting, Length: 2107, dtype: float64

In [30]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [31]:
from sklearn.naive_bayes import MultinomialNB

NB_classifier = MultinomialNB()
NB_classifier.fit(x_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [35]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = NB_classifier.predict(x_train)
y_pred
cm = confusion_matrix(y_train, y_pred)
cm

array([[1198,    2],
       [ 294,  191]])